### ISSUE TITLE
HTTP method types

### ISSUE THREAD

**Issue by singpolyma** [aristidb/http-types#41] opened 2013-10-26 16:47 UTC
Instead of having a (fairly useless) type synonym for HTTP method, and then a (fairly restrictive) enumeration of so-called "standard methods", why not have:

    data Method = GET | POST | PROPFIND | ... | OtherMethod ByteString

**Comment by aristidb** [comment] 2015-10-22 18:29
Closing as "Won't fix". It's a feature, not a bug! ;-)

**Closed by aristidb** 2015-10-22 18:29 UTC
